beyond-all-reason/spads_config_bar

etc/CaptainsDraftPlugin.conf
etc/CaptainsDraftPluginCmd.conf
etc/spads.conf
var/plugins/CaptainsDraftPluginHelp.dat
var/plugins/captainsdraftplugin.py

First version of captains draft plugin, code review would be appreciated.
Usage:
1. Usage: !preset captainsdraft
2. Everybody gets forced to spec and anybody who wishes to play must type !add
3. Players can !remove at any time, or leave the lobby, and the plugin will revert to the adding state
4. !draft must be called to begin the drafting phase. An even number of players is required to begin drafting with at least 6 players minimum
5. The two highest TS players are then automatically made captains of each team
6. The lowest TS of the two captains gets first pick. Players are picked with !pick [username]
7. Players are picked one after another, until all players are picked
8. Players must !cv start as normal
9. Once game has finished, plugin reverts to adding state and everybody who …

captains draft plugin

---

etc/commands.conf

Also made `!split` require a vote (I think)

Removed ability for specs to call several commands

---

pr-downloader.service
var/springsettings.cfg

CDN can be behind main repo, so let's make sure that when spads uses game update, it's available for everybody.

Make SPADs use CDN to download updates.

---

var/plugins/barmanager.py

SPADS `onPrivateMsg` handler will now scan for username called `Coordinator` (aka Teiserver)
if such user is messaging it will read the message and split with spaces to make array
the first array element is the command and the rest are arguments
additionally implemented a updateSkill handler, that hopefully parses additional player list and pokes SPADS to update their skill. 
To update the skill ratings the Teiserver should send a message to SPADS:
sample:
`updateSkill [DE]LSR Teifion Flash deltars`

teiserver message handler & updateSkill implementation

---

etc/mapLists.conf

Removes TMA20X 1.8 from the 8v8 map rotation (it was there on accident).

!nextmap rotation update

---

etc/spads.conf

> When a vote ends, SPADS prevents the user who started the vote to call another vote too fast, so that other users have some time to call a vote if they want to (vote flood protection). This is the minimum delay in seconds before someone can call another vote when his previous vote ended.
This change should hopefully reduce vote spam per user.

reCallVoteDelay from 10 to 30

---

etc/spads_cluster.conf
etc/spads_cluster_launcher.sh.template
var/plugins/LP_LargeTeamNb.pm

- adding LP_LargeTeamNb plugin for using unused bits in MYBATTLESTATUS for teamID and allyID > 16
- emptied CMD_autoLoadPlugins and set the plugin lis directly in spads_cluster.conf

LP_LargeTeamNb

---

etc/commands.conf

This change updates away-mode, "!vote b" votes or abstaining votes to effectively count as a "no" vote. 
The currently used `minVoteParticipation:50` value is set globally in `etc/spads.conf` and is being overriden only for the `!resign` command.
Currently, the following situation can occur and result in a successful team resign vote:
- 8 players
- 4 yes votes
- 1 no vote
- 3 abstained votes
Effectively 50% of the eligible voters can end the game.
With this change implemented, a 75% majority of explicit yes votes from the total eligible voters will be required for the vote to succeed.
Discussion & Context can be found [here](https://discord.com/channels/549281623154229250/1223834837727838299).
--- 
Applied the same change to the `!stop` command as well after a short discussion about it in …

Bump minVoteParticipation from 50 to 100 for team resign and stop command

---

etc/commands.conf
etc/commands_custom.conf

Update access requirements for !stop, !gKick, !gKick, !kick, and !kickBan commands while a game is running.
With the new access requirements, bosses are no longer able to unilaterally use those commands mid-game. Instead, a vote begins when a boss attempts to use them.
As a side effect, non-boss players in a boss-lobby are also able to initiate votes for the listed commands. This is necessary in-game, because otherwise only the boss would be eligible to vote.
It is not strictly necessary to allow non-boss votes when no game is running, but for consistency reasons this PR does allow that (as it doesn't make much sense to allow users to vote in game but not in lobby).

Prevent certain unilateral boss votes during running games.

---

etc/BarManagerCmd.conf
var/plugins/BarManagerHelp.dat
var/plugins/barmanager.py

Add !gatekeeper, !meme, and !balancealgorithm commands.
Note: "!balancealgorithm" is equivalent to "$balancemode". A new name was needed because there is an existing "!balancemode" command in SPADS, with a different purpose.
With this PR, all $-commands which require boss privileges should now have votable !-command versions.

Make all remaining boss-only $-commands votable (as !-commands).

---

var/plugins/barmanager.py
var/plugins/ratingmanager.py

BarManager removes the Teaser when the last player leaves a lobby.
But, currently it does not have a corresponding check for whether a Teaser should be set when a first player joins the lobby. This patch adds such a check; this makes it so that the Teaser will be updated quickly (before a configuration change is made).

Update teaser on first player join

---

etc/BarManagerCmd.conf
var/plugins/BarManagerHelp.dat
var/plugins/barmanager.py

Add a votable !-command version of the existing "$setratinglevels" command from Teiserver.
(Somehow I managed to miss this one, when I was making my list of $-commands to work on...)
The following commands were tested with this change in place, and I confirmed that the expected result occurred for each (either syntax error or clamping+applying the requested limits):
```
!setratinglevels 10 20
!setratinglevels 1 1
!setratinglevels 0 0
!setratinglevels 1000 1000
!setratinglevels 50 50
!setratinglevels 50 0
!setratinglevels 10 0
!setratinglevels 0 10
!setratinglevels 999 0
!setratinglevels 1000 0
!setratinglevels 9999 9999
!setratinglevels a a
!setratinglevels a 1
!setratinglevels 1 a
!setratinglevels 1 1 1
!setratinglevels
!setratinglevels a
!setratinglevels 1
```

Add "!setratinglevels" command.

---

etc/commands_custom.conf
etc/commands_default.conf
var/plugins/barmanager.py

_(I'll write up a proposed announcement tomorrow, but this can be reviewed for now at least)_
_(Also, https://github.com/beyond-all-reason/teiserver/pull/382 and https://github.com/beyond-all-reason/spads_config_bar/pull/137 should be merged/deployed before this PR)_
This patch makes two changes:
First, logic is added to `preSpadsCommand()` which blocks commands of the form "!callvote boss USERNAME" when:
- There is more than one **player** in the lobby
- AND, the caller has accessLevel < 100 (not a boss/mod/admin)
(Note that SPADS implicitly converts "!boss ..." to "!callvote boss ..." when the caller is low-privileged.)
Second, spectators with accessLevel 100 (already a boss) are permitted to use the "!boss" command. This makes it more convenient to transfer boss privileges to another …

Prevent electing bosses for lobbies with more than one player.

---

var/plugins/barmanager.py
var/plugins/ratingmanager.py

Currently, sendTachyonBattleTeaser() returns early if the lobby has a password set. With this change, an empty string is used as the Teaser instead.
This change is intended to make the function more robust; if a Teaser happens to be set when it shouldn't be, then the function now has a way to correct that.

Set empty teaser for private lobbies

---

var/plugins/barmanager.py

More changes arising from #142
Previously, a "Boss:" Teaser would conditionally be used. With this
patch, the "Boss:" entry is never included in the Teaser.
Additionally, when the "Team" and "Custom" presets are in use (and
there are no bots), the name of the preset is not displayed. For
example:
Before change: ` | Team 8v8`
After change:  ` | 8v8`
Before change: ` | Custom 4v4v4v4`
After change: ` | 4v4v4v4`
This does not apply when bots are configured. In such cases, the
preset name is still included (same behavior as before). For
example:
- ` | Team vs Scavengers`
- ` | Custom vs Raptors`
- ` | Coop vs AI`

Completely remove "Boss:" from Teasers, and hide preset when sane.

---

var/plugins/barmanager.py

This PR consists of one bugfix and one minor functional change.
____
Bugfix: In lobbies with multiple bosses, if a specific boss leaves the lobby then the crown is no longer displayed for the remaining bosses. (Note that the remaining bosses do still have boss privileges; this is a cosmetic issue.)
To test this fix, the following steps can be used:
1. USER_A: Join lobby
2. USER_A: Claim boss for self
3. USER_B: Join lobby
4. USER_A: Give boss to USER_B
5. USER_A: Run `!barmanagerprintstate`, observe that `whoIsBoss` = USER_B
6. USER_B: Leave lobby
Result on current code:
- USER_A no longer has a crown (broken)
- `!status` output shows that USER_A is still boss (correct)
- `!barmanagerprintstate` output shows that `whoIsBoss` = None (broken)
Result with this PR:
- USER_A still has a crown …

Minor boss changes

---

etc/commands.conf
etc/commands_custom.conf
etc/commands_default.conf

The purpose of this PR is allow a custom preset boss to take breaks. With these changes, players can vote to start and can also balance (without vote).
Mostly fixes #134
Allowing force speccing can be a separate PR since it's non trivial.

Allow custom preset boss to take breaks

---

spads_config_bar_updater.py

Currently, `spads_config_bar_updater.py` executes the following command to fetch updates from this repository:
- `git pull https://github.com/beyond-all-reason/spads_config_bar.git`
However, the above command does not reconcile any divergences between the local and remote repositories. That is fine for how the `main` branch is used, but the `integration` branch frequently diverges from the `main` branch (either due to automatic map metadata updates, or manual rebasing/rewriting).
This patch replaces the above command with the following commands:
- `git fetch origin`: download (but do not merge/checkout) all tracked branches from the remote repo.
- `git reset --hard FETCH_HEAD`: Update git's index *and* the working tree to match the fetched HEAD.
- `git clean -xfdf`: Remove any leftover, …

Make update script discard all local changes during git updates.

---

var/plugins/BarManagerHelp.dat
var/plugins/barmanager.py

Teiserver (in prod) now no longer has loser_picks as a choice for balance algorithm. It is now either "default" or "split_noobs". Need to update SPADS too. loser_picks does get called by default algo in certain circumstances.
```
!balancealgorithm default
!balancealgorithm split_noobs
```
Ensure both commands work

replace loser_picks with default for allowed balance algos

---

etc/commands.conf
etc/spads_cluster.conf
var/plugins/InGameMute.pm
var/plugins/barmanager.py

Notable changes in this batch:
- Change how `boss` status is sent to Chobby, to fix some edge cases involving multiple bosses (#152 @DeviousNull)
-- Non-blocking companion PR: https://github.com/beyond-all-reason/BYAR-Chobby/pull/763
- Send `mutes` status to Chobby, so the UI can indicate when a player is restricted from chatting (#164 @DeviousNull)
-- Non-blocking companion PR: https://github.com/beyond-all-reason/BYAR-Chobby/pull/759
- Shorten the default vote duration from 45 to 30 seconds, and ring players when a vote starts (#165 @DeviousNull)
- Log who pauses/unpauses the game in Teiserver's chat log (#166 @DeviousNull)
- Make callouts to non-API SPADS handlers more robust, in case of a future incompatible SPADS update (#167 @DeviousNull)
- Allow players to vote on `!force` in …

Merge Integration -> Main

---

etc/battlePresets.conf

This updates the coop battle preset to allow the use of debugcommands.
Currently, players who want to set up a Coop vs AI lobby with terrain modifiers need to use either the team or custom presets.
**This presents the following issue:**
-The lobby balance must be disabled to ensure all AIs are placed on a single team.
-Disabling balance can result in player IDs overlapping with AI IDs.
-Wait for the lobby to fill with the exact number of players.
-Lock the lobby.
-Remove and then re-add the AI or use forceId. 
(If an extra player is in que, they will join and take an AI spot when re-adding the AI.)
By enabling debugcommands in the coop preset, players can set up coop vs AI lobbies with terrain modifiers and proper balance settings, simplifying the process. We could also consider adding …

Add debugcommands to the coop preset
